[project]
name = "miniproject3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "정원하", email = "gpdlekswl@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.25.0",
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.12",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "langsmith>=0.14.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "tzdata>=2026.4",
]

[project.scripts]
miniproject3 = "miniproject3:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
