[project]
name = "miniproject3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "정원하", email = "gpdlekswl@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
miniproject3 = "miniproject3:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
